### ISSUE TITLE
raw_depth_to_grayscale_centimeters problem

### ISSUE THREAD

**Issue by command-z-z** [TzabarDolev/carlablog#1]
```python

def process_depth(self, img):

    R = img[:, :, 0]
    G = img[:, :, 1]
    B = img[:, :, 2]

    normalized = (G + B * 256 + R * 256 * 256) / (256 * 256 - 1)
    in_centimeters = 100000 * normalized
 
    # Avoiding zero division
    in_centimeters = np.clip(in_centimeters, 0.1, np.max(in_centimeters))
```

what's wrong with the original code in https://carla.readthedocs.io/en/latest/ref_sensors/#depth-camera？

Secondly, ` normalized = (G + B * 256 + R * 256 * 256) / (256 * 256 - 1)` Is this line of code wrong? should divide by `256 * 256 * 256  - 1`.

**Comment by TzabarDolev** [comment]
As you said yourself, the denominator is incorrect in the original equation. If you divide by the original equation you get the wrong depth per pixel.

**Comment by command-z-z** [comment]
thank you for your reply:)

Now, I am doing a project, that uses a depth map from Carla's simulation to do TSDF-Fusion to get a 3d geometry. however, I met a problem. Sometimes the 3d mesh is terrible and I visualize the 3d point cloud from a depth map with intrinsic and extrinsic, The points of the same object are not in the same position, and there are ghost images(The top two in the picture below). So I guess the depth map precision has errors or maybe extrinsic imprecise. I use your code to process depth, but the result is more terrible(The bottom one in the picture below), I don't know why.

convert function like this, do you have any suggestions? Have more information about converting functions. I don't understand the rationale behind it.
```python
def convert_bgr_depth_image_to_meters(image_path):
    # Load the encoded depth image
    encoded_depth_image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED).astype(np.float32)

    # Decode the depth image, assuming BGR format
    depth_image_meters = encoded_depth_image[:, :, 2] + encoded_depth_image[:, :, 1] * 256 + encoded_depth_image[:, :, 0] * 256**2
    depth_image_meters /= (256**3 - 1)  # Normalize the value to 0-1
    depth_image_meters *= 1000  # Assuming the maximum depth is 1000 meters

    return depth_image_meters

def process_depth(img_path):

    img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED).astype(np.float32)
    B = img[:, :, 0]
    G = img[:, :, 1]
    R = img[:, :, 2]

    normalized = (G + B * 256 + R * 256 * 256) / (256 * 256 - 1)
    in_centimeters = 100000 * normalized
 
    # Avoiding zero division
    in_centimeters = np.clip(in_centimeters, 0.1, np.max(in_centimeters))
    return in_centimeters
```

![swappy-20231221_222013](https://github.com/TzabarDolev/carlablog/assets/71259900/32910189-7d8b-4847-8601-0b9e2c7fc595)

**Comment by command-z-z** [comment]
thank you, I solved my problem, the extrinsic has some error, not the depth map problem.
